UPDATE YourTable
SET YourColumn = CASE
    WHEN id % 2 = 0 THEN 'path/to/even/file'
    ELSE 'path/to/odd/file'
END
WHERE id IS NOT NULL;
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Therese Loveland', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Drucie Jouning', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Sheppard Tarbin', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Corrinne Jandl', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Ilyse Sidlow', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('1984', 'Maddalena Renvoys', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('1984', 'Henka Piller', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Rosamund Lishman', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Hershel Umbers', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Ulrich Faichney', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('1984', 'Angelia Ast', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Wells Giacomazzo', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Karly Sothcott', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('1984', 'Purcell McOwen', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Constancy McClure', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Shalna Horning', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Jammie Foskin', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Bard Delnevo', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Dee dee Jardin', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Cord Bonafacino', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('1984', 'Colline Appleby', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('1984', 'Artair Ledward', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('1984', 'Dieter Overstone', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('1984', 'Maddy Bernier', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('1984', 'Dehlia Dray', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('The Catcher in the Rye', 'Cob Fiorentino', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('The Catcher in the Rye', 'Gwenore Knudsen', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Hilliard Soggee', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('1984', 'Freddi Lardeur', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Elonore Estevez', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('1984', 'Marni Sansom', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Charyl Dowrey', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Petra Chellam', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('1984', 'Gunther Cowen', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Tera Rockell', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Cirilo Madle', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Lenore Baptista', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Tristan Bettaney', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('1984', 'Sylvia O''Sheils', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('1984', 'Jeth Cavaney', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Grethel Eagleston', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Elie Trengrove', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('The Catcher in the Rye', 'Verne Anwell', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Doe Hebbes', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('The Catcher in the Rye', 'Astrid Sage', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Elvis Barsham', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Eduardo Hards', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Inger Posvner', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Cara Moncreif', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Cassandry Lindell', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Rodrigo Brabin', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Nedda Haddick', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Pierce Janovsky', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Catriona Slark', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Lena McCoy', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Maurise Kloser', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Rodger Pulford', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Clarinda Jeyes', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('The Catcher in the Rye', 'Morly Ferrini', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Yanaton Tolcharde', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Jane Fawkes', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Zorana Breakspear', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('1984', 'Stevena Fraanchyonok', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('1984', 'Ninette Greenhalgh', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Garald Inker', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('1984', 'Cobb Winstanley', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('The Catcher in the Rye', 'Christoper Cocksedge', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Robby Richten', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('The Catcher in the Rye', 'Carson Baxill', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Ingmar Brignell', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Maurise Giffin', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Brett Rathke', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Conrade Margrie', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Harland Dammarell', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Levon Tidcombe', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('1984', 'Dare Arnould', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Syd Ogles', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Jorey Burlingham', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Baillie Tchir', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Anthe Enrrico', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Ginni Withrington', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Godwin Biernacki', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('The Catcher in the Rye', 'Curt Ram', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Simonette Kennett', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Lynnelle Fearenside', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Wynn Rayworth', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Thayne Umfrey', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Inga Sturm', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('The Catcher in the Rye', 'Rolando Escala', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('The Catcher in the Rye', 'Pavia Czaja', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Livvyy Bolderoe', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Lenna Guilliland', 'An epic fantasy adventure filled with magic and intrigue');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Freddie Earney', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Rustin Skeermer', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Haydon Scotford', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('1984', 'Willy Horsted', 'A gripping thriller with unexpected twists');
insert into Books (Name, Author, Description) values ('Pride and Prejudice', 'Casper Folbig', 'A heartwarming story of love and friendship');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Che Thamelt', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('The Great Gatsby', 'Arielle Crawcour', 'A captivating mystery that will keep you guessing');
insert into Books (Name, Author, Description) values ('To Kill a Mockingbird', 'Gussie Dumbrall', 'A gripping thriller with unexpected twists');
# Rows:
